### ISSUE TITLE
Recording not working if used twice

### ISSUE THREAD

**Issue by maxyodedara5** [Lime-Parallelogram/cj2022-stately-satyrs#26]
Open the notepad
Press the microphone, speak it writes to editor
Release press, it stops recording

Press the microphone again, there's an issue.

**Comment by maxyodedara5** [comment]
Log for debugging @GHandrea 

```debugging: func called
record terminated
calling API
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\Maxy\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Maxy\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "g:\Projects Aug 2021 Onward\cj2022-stately-satyrs\desktop-gui\recorder.py", line 52, in record
    self.stream = self.p.open(rate=self.SAMPLE_RATE,
  File "C:\Users\Maxy\AppData\Local\Programs\Python\Python39\lib\site-packages\pyaudio.py", line 754, in open
    stream = Stream(self, *args, **kwargs)
  File "C:\Users\Maxy\AppData\Local\Programs\Python\Python39\lib\site-packages\pyaudio.py", line 445, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid input device (no default output device)
debugging: func called
record terminated
calling API
PS G:\Projects Aug 2021 Onward\cj2022-stately-satyrs\desktop-gui>

**Comment by maxyodedara5** [comment]
Issue has been fixed, closing this item
